### ISSUE TITLE
Phase 1 User Stories

### ISSUE THREAD

**Issue by aidanmcgraw** [malvarez0722/ee461l-team-project#1]
As a potential voter who is bored by politics, I want to be able to quickly find succinct, relevant info about the politicians that will be on my ballot, so that I can be relatively informed if I choose to go vote.

**Comment by aidanmcgraw** [comment]
As an elderly voter who is not so tech-literate, I want to see how my representatives have voted recently so that I can determine if my representatives are voting the way I want on the issues that are important to me.

**Comment by aidanmcgraw** [comment]
As an avid Bernie Bro, I want to see when and where Bernie’s upcoming rallies in the next month are, so that I can decide which events I will be able to attend.

**Comment by aidanmcgraw** [comment]
As a person who distrusts politicians, I want to see which organizations donate to major politicians and the voting history of any politician so that I can know who to vote out of office.

**Comment by aidanmcgraw** [comment]
As a wealthy owner of a natural gas company, I want to see who has been speaking out against fracking so that I can finance their political opponents.

**Comment by bailloj** [comment]
As a young Asian American, I want to find out the demographics of voters for certain politicians by age and race so I can know who people like me are voting for.

**Comment by aidanmcgraw** [comment]
As a high school government teacher, I want to thoroughly comb through recent US federal legislation regarding Environment Protection, so that I can show my students how energy policy has evolved as we learn about the EPA.

**Comment by mtmn19** [comment]
As a person who wants to get involved, I want to see grassroots events near me affiliated with the parties I support.

**Comment by mtmn19** [comment]
As a student studying law, I want to view information about bills in certain topics so I can use the information in my school papers.

**Comment by mtmn19** [comment]
As a student interested in hot topics, I want to see legislation relating to trending issues.
